### ISSUE TITLE
-cache gcs://... failing: panic: invalid character 'A' looking for beginning of value

### ISSUE THREAD

**Issue by allenday** [willnorris/imageproxy#131]
command:
`imageproxy -cache gcs://my-bucket/my-path`

stacktrace:
```
panic: invalid character 'A' looking for beginning of value

goroutine 1 [running]:
panic(0xb188e0, 0xc420167ec0)
        /usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
willnorris.com/go/imageproxy/vendor/github.com/diegomarangoni/gcscache.New(0xc420167ea0, 0x17, 0x17)
        /var/www/gocode/src/willnorris.com/go/imageproxy/vendor/github.com/diegomarangoni/gcscache/gcscache.go:88 +0x7ea
main.parseCache(0x7fff8c138863, 0x17, 0x40dc41, 0xc06868, 0x7fff8c13885d, 0x5)
        /var/www/gocode/src/willnorris.com/go/imageproxy/cmd/imageproxy/main.go:145 +0x1c1
main.(*tieredCache).Set(0x1016170, 0x7fff8c138863, 0x17, 0xc42021dd00, 0xc4201c5400)
        /var/www/gocode/src/willnorris.com/go/imageproxy/cmd/imageproxy/main.go:113 +0x3f
flag.(*FlagSet).parseOne(0xc4200180c0, 0x0, 0xc42021de18, 0x45e760)
        /usr/lib/go-1.7/src/flag/flag.go:896 +0x259
flag.(*FlagSet).Parse(0xc4200180c0, 0xc42000c100, 0x2, 0x2, 0x0, 0x0)
        /usr/lib/go-1.7/src/flag/flag.go:915 +0x60
flag.Parse()
        /usr/lib/go-1.7/src/flag/flag.go:943 +0x72
main.main()
        /var/www/gocode/src/willnorris.com/go/imageproxy/cmd/imageproxy/main.go:60 +0x47
```

**Comment by allenday** [comment]
hello

**Comment by willnorris** [comment]
We talked about this over chat and determined it was an issue with his GCS credentials.  I've since changed the GCS caching implementation we're using so that it uses Google's standard Application Default Credentials, which should work much better.
